FROM "{{ distro }}:{{ image_version }}"

RUN apt-get update -y && \
    apt-get install --fix-missing && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
        sudo curl gcc libffi-dev libssl-dev \
    {%- if python3.enabled %}
        python3 python3-pip python3-dev python3-yaml \
    {%- else %}
        python python-pip python-dev python-yaml \
    {%- endif %}
    {%- if java.enabled %}
        openjdk-8-jre \
    {%- endif %}
        sshpass openssh-client && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/*

RUN {% if python3.enabled -%}
    ln -s $(which python3) $(dirname $(which python3))/python && \
    ln -s $(which python3) /usr/local/bin/python && \
    pip3 install -U pip && \
{%- else -%}
    easy_install -U pip && \
{%- endif %}
    pip install -U setuptools pyopenssl && \
    pip install -U --ignore-installed cffi pywinrm && \
    pip install ansible=={{ ansible.version }} && \
    # Adding Ansible hosts for convenience
    mkdir -p /etc/ansible && \
    echo 'localhost' > /etc/ansible/hosts

ENTRYPOINT [ "ansible-playbook" ]
