{%- extends "base/Dockerfile.jinja2" -%}

{%- block os_packages -%}
RUN apt-get update -y && \
    apt-get install --fix-missing && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
        sudo curl gcc libffi-dev libssl-dev iproute2 \
    {%- if python3.enabled %}
        python3 python3-pip python3-dev python3-yaml python3-apt \
    {%- else %}
        python python-pip python-dev python-yaml \
    {%- endif %}
    {%- if java.enabled %}
        $(apt-cache search --names-only '^openjdk-(8|11)-jre$' | \
            awk '{ print $1 }') \
    {%- endif %}
        sshpass openssh-client && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/*
{%- endblock %}
