FROM "{{ distro | default('alpine') }}:{{ image_version }}"

RUN apk --update --no-cache add sudo \
        openssl ca-certificates \
        libffi-dev openssl-dev build-base \
{%- if python3.enabled %}
        python3-dev python3 py3-pip \
{%- else %}
        python-dev python py-pip \
{%- endif %}
{%- if java.enabled %}
        openjdk8-jre-base \
{%- endif %}
        openssh-client rsync sshpass && \
{%- if python3.enabled %}
    ln -s $(which python3) $(dirname $(which python3))/python && \
    ln -s $(which python3) /usr/local/bin/python && \
    pip3 install -U pip && \
{%- endif %}
    pip install -U pip cffi pywinrm && \
    pip install ansible=={{ ansible.version }} && \
    # Adding hosts for convenience
    mkdir -p /etc/ansible && \
    echo 'localhost' > /etc/ansible/hosts

ENTRYPOINT [ "ansible-playbook" ]
