{%- extends "base/Dockerfile.jinja2" -%}

{%- block os_packages -%}
RUN apk --update --no-cache add sudo \
        openssl ca-certificates bash \
        tar gzip iproute2 \
        libffi-dev openssl-dev build-base \
{%- if python3.enabled %}
        python3-dev python3 py3-pip \
{%- else %}
        python-dev python py-pip \
{%- endif %}
{%- if java.enabled %}
        openjdk8-jre-base \
{%- endif %}
        openssh-client rsync sshpass
{%- endblock %}
